services:
  mysql_todolist:
    image: mysql:5.7
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    command: --default-authentication-plugin=mysql_native_password

  my_todoapp:
    restart: always
    build: .
    image: my_todoapp
    depends_on:
      - mysql_todolist
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge