services:
  my_todoapp:
    restart: always
    build: .
    depends_on:
      - mysql_todolist
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  mysql_todolist:
    image: mysql:5.7
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "5000:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: